
package com.ebay.services.product;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProductService", targetNamespace = "http://www.ebay.com/marketplace/marketplacecatalog/v1/services", wsdlLocation = "ProductService.wsdl")
public class ProductService
    extends Service
{

    private final static URL PRODUCTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTSERVICE_EXCEPTION;
    private final static QName PRODUCTSERVICE_QNAME = new QName("http://www.ebay.com/marketplace/marketplacecatalog/v1/services", "ProductService");

    static {
        PRODUCTSERVICE_WSDL_LOCATION = com.ebay.services.product.ProductService.class.getResource("ProductService.wsdl");
        WebServiceException e = null;
        if (PRODUCTSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'ProductService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PRODUCTSERVICE_EXCEPTION = e;
    }

    public ProductService() {
        super(__getWsdlLocation(), PRODUCTSERVICE_QNAME);
    }

    public ProductService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTSERVICE_QNAME, features);
    }

    public ProductService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTSERVICE_QNAME);
    }

    public ProductService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTSERVICE_QNAME, features);
    }

    public ProductService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductServicePortType
     */
    @WebEndpoint(name = "ProductServiceSOAP12port_http")
    public ProductServicePortType getProductServiceSOAP12PortHttp() {
        return super.getPort(new QName("http://www.ebay.com/marketplace/marketplacecatalog/v1/services", "ProductServiceSOAP12port_http"), ProductServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductServicePortType
     */
    @WebEndpoint(name = "ProductServiceSOAP12port_http")
    public ProductServicePortType getProductServiceSOAP12PortHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ebay.com/marketplace/marketplacecatalog/v1/services", "ProductServiceSOAP12port_http"), ProductServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTSERVICE_EXCEPTION!= null) {
            throw PRODUCTSERVICE_EXCEPTION;
        }
        return PRODUCTSERVICE_WSDL_LOCATION;
    }

}
