
package com.ebay.services.product;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductServicePortType", targetNamespace = "http://www.ebay.com/marketplace/marketplacecatalog/v1/services")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductServicePortType {


    /**
     * 
     * @param params
     * @return
     *     returns com.ebay.services.product.FindProductsResponse
     */
    @WebMethod(action = "urn:findProducts")
    @WebResult(name = "findProductsResponse", targetNamespace = "http://www.ebay.com/marketplace/marketplacecatalog/v1/services", partName = "params")
    public FindProductsResponse findProducts(
        @WebParam(name = "findProductsRequest", targetNamespace = "http://www.ebay.com/marketplace/marketplacecatalog/v1/services", partName = "params")
        FindProductsRequest params);

    /**
     * 
     * @param params
     * @return
     *     returns com.ebay.services.product.GetProductDetailsResponse
     */
    @WebMethod(action = "urn:getProductDetails")
    @WebResult(name = "getProductDetailsResponse", targetNamespace = "http://www.ebay.com/marketplace/marketplacecatalog/v1/services", partName = "params")
    public GetProductDetailsResponse getProductDetails(
        @WebParam(name = "getProductDetailsRequest", targetNamespace = "http://www.ebay.com/marketplace/marketplacecatalog/v1/services", partName = "params")
        GetProductDetailsRequest params);

    /**
     * 
     * @param params
     * @return
     *     returns com.ebay.services.product.FindProductsResponse
     */
    @WebMethod(action = "urn:findProductsByCompatibility")
    @WebResult(name = "findProductsByCompatibilityResponse", targetNamespace = "http://www.ebay.com/marketplace/marketplacecatalog/v1/services", partName = "params")
    public FindProductsResponse findProductsByCompatibility(
        @WebParam(name = "findProductsByCompatibilityRequest", targetNamespace = "http://www.ebay.com/marketplace/marketplacecatalog/v1/services", partName = "params")
        FindProductsByCompatibilityRequest params);

    /**
     * 
     * @param params
     * @return
     *     returns com.ebay.services.product.GetProductCompatiblitiesResponse
     */
    @WebMethod(action = "urn:getProductCompatibilities")
    @WebResult(name = "getProductCompatibilitiesResponse", targetNamespace = "http://www.ebay.com/marketplace/marketplacecatalog/v1/services", partName = "params")
    public GetProductCompatiblitiesResponse getProductCompatibilities(
        @WebParam(name = "getProductCompatibilitiesRequest", targetNamespace = "http://www.ebay.com/marketplace/marketplacecatalog/v1/services", partName = "params")
        GetProductCompatibilitiesRequest params);

    /**
     * 
     * @param params
     * @return
     *     returns com.ebay.services.product.FindCompatibilitiesBySpecificationResponse
     */
    @WebMethod(action = "urn:findCompatibilitiesBySpecification")
    @WebResult(name = "findCompatibilitiesBySpecificationResponse", targetNamespace = "http://www.ebay.com/marketplace/marketplacecatalog/v1/services", partName = "params")
    public FindCompatibilitiesBySpecificationResponse findCompatibilitiesBySpecification(
        @WebParam(name = "findCompatibilitiesBySpecificationRequest", targetNamespace = "http://www.ebay.com/marketplace/marketplacecatalog/v1/services", partName = "params")
        FindCompatibilitiesBySpecificationRequest params);

    /**
     * 
     * @param params
     * @return
     *     returns com.ebay.services.product.GetProductSubmissionsResponse
     */
    @WebMethod(action = "urn:getProductSubmissions")
    @WebResult(name = "getProductSubmissionsResponse", targetNamespace = "http://www.ebay.com/marketplace/marketplacecatalog/v1/services", partName = "params")
    public GetProductSubmissionsResponse getProductSubmissions(
        @WebParam(name = "getProductSubmissionsRequest", targetNamespace = "http://www.ebay.com/marketplace/marketplacecatalog/v1/services", partName = "params")
        GetProductSubmissionsRequest params);

    /**
     * 
     * @param params
     * @return
     *     returns com.ebay.services.product.AddProductsResponse
     */
    @WebMethod(action = "urn:addProducts")
    @WebResult(name = "addProductsResponse", targetNamespace = "http://www.ebay.com/marketplace/marketplacecatalog/v1/services", partName = "params")
    public AddProductsResponse addProducts(
        @WebParam(name = "addProductsRequest", targetNamespace = "http://www.ebay.com/marketplace/marketplacecatalog/v1/services", partName = "params")
        AddProductsRequest params);

}
